resolver: lts-7.19

packages:
- '.'
- location:
    git: https://github.com/futurice/haskell-tdigest
    commit: 7b16d730b84b1fca2f97dfa3862d5781856d19e9
  extra-dep: true

extra-deps:
  - rdtsc-1.3.0.1
